#!/usr/bin/env python3
"""Download the site's webfonts from Google and self-host them.

Until the 2026-09-14 audit (M-11) the site linked fonts.googleapis.com on every
page. That blocked the first paint on a third-party connection, and sent every
EU visitor's IP address to Google before they had consented to anything.

Writes site/public/fonts/*.woff2 and site/public/fonts/fonts.css.
Only the latin and latin-ext subsets are kept — the site is English.

Note: Google serves VARIABLE Archivo and IBM Plex Sans, so one file covers all
their weights. IBM Plex Mono is static, one file per weight. The script
de-duplicates on URL, so it handles either.

    python3 scripts/fetch-fonts.py
"""
import pathlib, re, subprocess, sys, urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "site/public/fonts"
KEEP = {"latin", "latin-ext"}
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

# Must match the families and weights system.css actually asks for.
CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Archivo:wght@400;500;600;700;800"
           "&family=IBM+Plex+Mono:wght@400;500"
           "&family=IBM+Plex+Sans:wght@400;500;600"
           "&display=swap")


def main() -> int:
    req = urllib.request.Request(CSS_URL, headers={"User-Agent": UA})
    css = urllib.request.urlopen(req, timeout=30).read().decode()

    blocks = re.findall(r"/\*\s*([a-z0-9-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S)
    if not blocks:
        sys.exit("no @font-face blocks — Google's CSS format changed?")

    OUT.mkdir(parents=True, exist_ok=True)

    # One filename per distinct URL, so a variable font is downloaded once.
    name_for: dict[str, str] = {}
    for subset, b in blocks:
        if subset not in KEEP:
            continue
        url = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", b).group(1)
        if url in name_for:
            continue
        fam = re.search(r"font-family: '([^']+)'", b).group(1)
        wt = re.search(r"font-weight: ([\d ]+);", b).group(1).strip().replace(" ", "-")
        slug = fam.lower().replace(" ", "-")
        cand, n = f"{slug}-{wt}-{subset}.woff2", 1
        while cand in name_for.values():
            n += 1
            cand = f"{slug}-{wt}-{subset}-{n}.woff2"
        name_for[url] = cand

    kept = []
    for subset, b in blocks:
        if subset not in KEEP:
            continue
        url = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", b).group(1)
        kept.append(b.replace(url, f"/fonts/{name_for[url]}"))

    total = 0
    for url, name in name_for.items():
        dest = OUT / name
        subprocess.run(["curl", "-sS", "-A", UA, url, "-o", str(dest)], check=True)
        total += dest.stat().st_size

    header = (
        "/* Self-hosted webfonts — GENERATED by scripts/fetch-fonts.py.\n"
        "   Subsets: latin + latin-ext. Do not hand-edit; re-run the script. */\n"
    )
    (OUT / "fonts.css").write_text(header + "\n".join(kept) + "\n", encoding="utf-8")

    out_css = (OUT / "fonts.css").read_text()
    missing = [m for m in re.findall(r"url\(/fonts/([^)]+)\)", out_css) if not (OUT / m).exists()]
    print(f"{len(kept)} @font-face rules -> {len(name_for)} files, {total/1024:.0f} KB")
    if missing:
        sys.exit(f"BROKEN: CSS references files that were not written: {missing}")
    print("all references resolve")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
